service:
  name: netplan
  config:
    source: templates/60-floating-ip.yaml
    desination: /etc/netplan/60-floating-ip.yaml
    watching_key:
      leader_ip
    this_host_swarm_ip: 10.1.0.14
    commands:
      - /usr/sbin/netplan apply



